# Generated by Django 5.2 on 2025-04-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="class_name",
            new_name="year",
        ),
        migrations.AlterField(
            model_name="student",
            name="roll_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "date")},
        ),
    ]
